services:
  app:
    build: .
    container_name: asgard_app
    ports:
      - "8080:8080"
    networks:
      - asgard-network
    depends_on:
      postgres-db:
        condition: service_healthy

  postgres-db:
    image: postgres:15-alpine
    container_name: asgard_postgres
    environment:
      POSTGRES_DB: asgard_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - asgard-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d asgard_db" ]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  postgres_data:
  mongo_data:

networks:
  asgard-network:
    driver: bridge