services:
  app:
    build: .
    container_name: asgard_app
    ports:
      - "8080:8080"
    depends_on:
      ollama:
        condition: service_healthy
    networks:
      - asgard-network
    environment:
      - JAVA_OPTS="-Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true"

  postgres-db:
    image: postgres:15-alpine
    container_name: asgard_postgres
    environment:
      POSTGRES_DB: asgard_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - asgard-network

  mongo-db:
    image: mongo:7
    container_name: asgard_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: your_password
    volumes:
      - mongo_data:/data/db
    networks:
      - asgard-network

  ollama:
    image: ollama/ollama:latest
    container_name: asgardOllama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    tty: true
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=0.0.0.0
    command: serve
    healthcheck:
      test: [ "CMD", "ollama", "list" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - asgard-network

volumes:
  postgres_data:
  mongo_data:
  ollama_data:

networks:
  asgard-network:
    driver: bridge